=== mbutler/schema/SET_OF_PAGES.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT PAGE (TEXT)>
<!ATTLIST PAGE
PERIMETER CDATA #REQUIRED
PAPER_STOCK CDATA #IMPLIED
PAPER_WEIGHT CDATA #IMPLIED>

<!ELEMENT TEXT (COLUMN+)>
<!ATTLIST TEXT 
PERCENT_OF_PAGE CDATA #REQUIRED
FONT CDATA #REQUIRED
DEPRESSIONS_ON_SURFACE CDATA #IMPLIED
FONT_SIZE CDATA #REQUIRED>

<!ELEMENT COLUMN (LINE+)>
<!ELEMENT LINE (WORD+)>
<!ELEMENT WORD (DATA)>
<!ELEMENT DATA (#PCDATA) >
<!ATTLIST WORD
 CAPITALIZED (YES | NO) "NO"
 ITALICIZED (YES | NO) "NO"
 NUMBER_OF_LETTERS CDATA #REQUIRED
 PART_OF_SPEECH  (ADJECTIVE | ADVERB | CONJUNCTION | GERUND | INFINITIVE | NOUN | MATH_SYMBOL | NUMERAL | PREPOSITION | PRONOUN | PARTICIPLE | NA) "NOUN">

=== mbutler/schema/fofum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PAGE SYSTEM "http://www.mbutler.org/schema/SET_OF_PAGES.dtd">
<?xml-stylesheet type="text/css" href="page.css"?>
<PAGE PERIMETER="0" PAPER_STOCK="NA" PAPER_WEIGHT="NA">
    <TEXT PERCENT_OF_PAGE="20" FONT="GARAMOND" FONT_SIZE="12">
        <COLUMN>
            <LINE>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="YES" ITALICIZED="NO"  PART_OF_SPEECH="NA">
                    <DATA>Fee!</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>Fie!</DATA>
                </WORD>
                 <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                     <DATA>Foe!</DATA>
                 </WORD>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>Fum!</DATA>
                </WORD>
            </LINE>
            <LINE>
                <WORD NUMBER_OF_LETTERS="1" CAPITALIZED="YES" ITALICIZED="NO"  PART_OF_SPEECH="PRONOUN">
                    <DATA>I</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>smell</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>the</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>blood</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="PREPOSITION">
                    <DATA>of</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>an</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="10" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>Englishman.</DATA>
                </WORD>
            </LINE>
            <LINE>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>Be</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>he</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="ADJECTIVE">
                    <DATA>'live</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="CONJUNCTION">
                    <DATA>or</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>be</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="PRONOUN">
                    <DATA>he</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="ADVERB">
                    <DATA>dead,</DATA>
                </WORD>
            </LINE>
            <LINE>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="PRONOUN">
                    <DATA>I'll</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>grind</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="PRONOUN">
                    <DATA>his</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>bones</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="INFINITIVE">
                    <DATA>to</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>make</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="PRONOUN"> 
                    <DATA>my</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>bread.</DATA>
                </WORD>
            </LINE>
        </COLUMN>
    </TEXT>
</PAGE>

=== mbutler/schema/birds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PAGE SYSTEM "http://www.mbutler.org/schema/SET_OF_PAGES.dtd">
<?xml-stylesheet type="text/css" href="page.css"?>
<PAGE PERIMETER="0" PAPER_STOCK="NA" PAPER_WEIGHT="NA">
    <TEXT PERCENT_OF_PAGE="20" FONT="GARAMOND" FONT_SIZE="12">
        <COLUMN>
            <LINE>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>Birds</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="PREPOSITION">
                    <DATA>of</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="1" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>a</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="7" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>feather</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>flock</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="8" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="ADVERB">
                    <DATA>together,</DATA>
                </WORD>
            </LINE>
            <LINE>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="CONJUNCTION">
                    <DATA>And</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="ADVERB">
                    <DATA>so</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>will</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>pigs</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="CONJUNCTION">
                    <DATA>and</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>swine;</DATA>
                </WORD>
            </LINE>
            <LINE>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>Rats</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="CONJUNCTION">
                    <DATA>and</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>mice</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>will</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>have</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="5" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="PRONOUN">
                    <DATA>their</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="6" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NOUN">
                    <DATA>choice,</DATA>
                </WORD>
            </LINE>
            <LINE>
                <WORD NUMBER_OF_LETTERS="3" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="CONJUNCTION">
                    <DATA>And</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="2" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="ADVERB">
                    <DATA>so</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>will</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="1" CAPITALIZED="YES" ITALICIZED="NO" PART_OF_SPEECH="PRONOUN">
                    <DATA>I</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO" PART_OF_SPEECH="NA">
                    <DATA>have</DATA>
                </WORD>
                <WORD NUMBER_OF_LETTERS="4" CAPITALIZED="NO" ITALICIZED="NO">
                    <DATA>mine.</DATA>
                </WORD>
            </LINE>
        </COLUMN>
    </TEXT>
</PAGE>
